export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const UPDATE_PRIORITY = 'UPDATE_PRIORITY';
export const REORDER_LIST = 'REORDER_LIST';